export const ACTION_TYPES = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  REGISTERED: 'REGISTERED',
  EDIT_NAME_USER: 'EDIT_NAME_USER',
  EDIT_EMAIL_USER: 'EDIT_EMAIL_USER',
  EDIT_PASSWORD_USER: 'EDIT_PASSWORD_USER',
};
