import { nanoid } from 'nanoid';

export interface IPlant {
  id?: string;
  name: string;
  description?: string;
  popularity?: number;
  category?: string;
  price?: number;
  count?: number;
  priceTotal?: number;
}

export const plants: IPlant[] = [
  {
    id: nanoid(),
    name: 'Calathea Silhouette',
    description: 'thvihrihvovm fghtunjnyfght  fghytjnrbhbnv',
    popularity: 8,
    category: 'Foliage',
    price: 23,
    count: 1,
    priceTotal: 23,
  },
  {
    id: nanoid(),
    name: 'Minature',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 16,
    category: 'Foliage',
    price: 5,
    count: 1,
    priceTotal: 5,
  },
  {
    id: nanoid(),
    name: 'Veitchiana Hook',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 5,
    category: 'Foliage',
    price: 150,
    count: 1,
    priceTotal: 150,
  },
  {
    id: nanoid(),
    name: 'Orbifolia',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 1,
    category: 'Foliage',
    price: 33,
    count: 1,
    priceTotal: 33,
  },
  {
    id: nanoid(),
    name: 'Ryvrbifolia',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 1,
    category: 'Foliage',
    price: 74,
    count: 1,
    priceTotal: 74,
  },
  {
    id: nanoid(),
    name: 'Calathea Silhouette',
    description: 'thvihrihvovm fghtunjnyfght  fghytjnrbhbnv',
    popularity: 8,
    category: 'Foliage',
    price: 9,
    count: 1,
    priceTotal: 9,
  },
  {
    id: nanoid(),
    name: 'Orbifolia',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 1,
    category: 'Foliage',
    price: 96,
    count: 1,
    priceTotal: 96,
  },
  {
    id: nanoid(),
    name: 'Veitchiana Hook.',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 10,
    category: 'Succulent',
    price: 50,
    count: 1,
    priceTotal: 50,
  },
  {
    id: nanoid(),
    name: 'Lietzei `Fusion White`',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 7,
    category: 'Succulent',
    price: 42,
    count: 1,
    priceTotal: 42,
  },
  {
    id: nanoid(),
    name: 'Monstera Deliciosa',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 17,
    category: 'Succulent',
    price: 11,
    count: 1,
    priceTotal: 11,
  },
  {
    id: nanoid(),
    name: 'Anthurium Clarinervium',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 3,
    category: 'Succulent',
    price: 88,
    count: 1,
    priceTotal: 88,
  },
  {
    id: nanoid(),
    name: 'Calathea Lietzei `Fusion White`',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 7,
    category: 'Flower',
    price: 63,
    count: 1,
    priceTotal: 63,
  },
  {
    id: nanoid(),
    name: 'Feliciosa',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 19,
    category: 'Flower',
    price: 14,
    count: 1,
    priceTotal: 14,
  },
  {
    id: nanoid(),
    name: 'Unthurium Clarinervium',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 12,
    category: 'Flower',
    price: 8,
    count: 1,
    priceTotal: 8,
  },
  {
    id: nanoid(),
    name: 'Lietzei `Fusion White`',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 6,
    category: 'Flower',
    price: 113,
    count: 1,
    priceTotal: 113,
  },
  {
    id: nanoid(),
    name: 'Teliciosa',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 9,
    category: 'Fruit',
    price: 29,
    count: 1,
    priceTotal: 29,
  },
  {
    id: nanoid(),
    name: 'Nlarinervium',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 14,
    category: 'Fruit',
    price: 37,
    count: 1,
    priceTotal: 37,
  },
  {
    id: nanoid(),
    name: 'Neliciosa',
    description: 'kdfbgbtkb fbhrtin ghirtnb hgjitjrobm 133r438hvj',
    popularity: 9,
    category: 'Fruit',
    price: 18,
    count: 1,
    priceTotal: 18,
  },
];
